### ISSUE TITLE
cache still broken

### ISSUE THREAD

**Issue by stevezau** [hauxir/imgpush#16]
Hi,

We are using the fix here https://github.com/hauxir/imgpush/pull/14

however, after a while, we are now getting exhausted errors again, the /tmp is filled up to 8gb with files. 

So i think there is an issue where the temp files are not being deleted. Now sure how to t-shoot this?

**Comment by hauxir** [comment]
Did you update the image after this merge https://github.com/hauxir/imgpush/pull/15 ?

**Comment by stevezau** [comment]
oh, i missed that. great.

**Comment by stevezau** [comment]
@hauxir i assume latest tag has this fix also?

**Comment by hauxir** [comment]
> @hauxir i assume latest tag has this fix also?

latest is built using the latest master :)
