### ISSUE TITLE
Guessing why pictures is not loading when working without nginx and gunicorn

### ISSUE THREAD

**Issue by yumupdate** [hauxir/imgpush#31]
I'm trying to understand why my browser is telling me that picture is broken when I'm trying to open it without nginx and gunicorn.
I've created a vevn that contains all required packages and installed packages from the docker file on my system, then I'm starting the app and I am able to upload img able but I can't open the image in the browser, when I starting nginx images begins loading normally.

Can't understand why images are not loading without nginx?

**Comment by hauxir** [comment]
try disabling this https://github.com/hauxir/imgpush/blob/master/app/app.py#L29

**Comment by yumupdate** [comment]
> try disabling this https://github.com/hauxir/imgpush/blob/master/app/app.py#L29

Thank you very much!
I can confirm it's working, but why you used this options? is there any benefits?

Just read it, yeah there benefits from this.
