### ISSUE TITLE
CacheError

### ISSUE THREAD

**Issue by stevezau** [hauxir/imgpush#9]
Hi

I am getting this after a few days of uptime

```wand.exceptions.CacheError: cache resources exhausted `/tmp/SlRb2' @ error/cache.c/OpenPixelCache/4083```

Is this a memory thing? any suggestions?

Pod us using 1GB memory atm. Seems high.

**Comment by pdelaby** [comment]
I had a similar problem, in my case I think it was related to ImageMagick. I modified the Dockerfile in order to set a custom configuration for ImageMagick, maybe it can work for you too ? 
cf https://github.com/pdelaby/imgpush/commit/f683f2e73490f20ec244407beac0aa09e23fef1c

**Comment by hauxir** [comment]
If you have a fix for this please make a PR!

I've found that I have to clear the cache every few days but I haven't had time to look into the issue.

**Comment by stevezau** [comment]
@hauxir how do you clear the cache?

**Comment by stevezau** [comment]
I'm testing with the resources restrictions commented out in /etc/ImageMagick-6/policy.xml

**Comment by hauxir** [comment]
I basically shell into the container an remove all the imagemagick stuff in /tmp/

**Comment by stevezau** [comment]
@hauxir ah ok, i think that is a different bug, this app should clean up even on error. I can see it has code to do that, to sure why it is not working.

**Comment by hauxir** [comment]
it only clears up the tmp file imgpush creates but it seems imagemagick itself is also saving some tmp files.
